language: php
php:
  - '7.0'
  
deploy:
  provider: heroku
  api_key: fb0a7462-9985-4979-a5e6-ccfc799d1d16
  app: quiet-falls-13166

before_script: composer install

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist
